### PR TITLE
DarkMode Toggle

### PR DESCRIPTION
**Pull request by moudgalya1223**

### CODE REVIEW

**Comment by jaiyankargupta** [comment]
@moudgalya1223 footer is not looking good in darkmode, it is still in light mode, please fix it

**Comment by RashmitTopG** [comment]
Fixed the UI a little bit and added Dark Mode

**Comment by moudgalya1223** [comment]
Please try now? hope this should fix thanks

**Comment by jaiyankargupta** [comment]
@moudgalya1223 when i active light mode, social icon is invisible.

**Pull request closed without merging**
